deployment:
  tasks:
    - /bin/mkdir -p /home/fitfaith/public_html
    - /bin/rsync -av --delete --exclude='.git*' --exclude='.github/' --exclude='*.md' ./ /home/fitfaith/public_html/
    - /bin/chmod -R 755 /home/fitfaith/public_html
    - /bin/find /home/fitfaith/public_html -type f -exec chmod 644 {} \;
